[package]
name = "ootr-gui"
version.workspace = true
edition.workspace = true

[lints.rust]
rust_2018_idioms = "deny"
#unsafe_code = "forbid" # PyO3 generates unsafe code
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[dependencies]
collect-mac = "0.1.0"
enum-iterator = "2.1.0"
futures = "0.3"
gres = { git = "https://github.com/fenhl/gres", branch = "main" }
iced = { version = "0.13", default-features = false, features = ["auto-detect-theme", "image", "multi-window", "tiny-skia", "tokio"] }
if_chain = "1.0.2"
image = { version = "0.24", default-features = false, features = ["ico"] } # transitive dependency of iced
indexmap = { version = "2.6.0", features = ["serde"] }
itertools = "0.14"
mimalloc = "0.1.44"
nonempty-collections = "0.3"
ootr-common = { version = "8.2.76-fenhl.1.riir.2", path = "../ootr-common" }
ootr-macros = { path = "../ootr-macros" }
pyo3 = { version = "0.24", features = [
    "auto-initialize",
    "indexmap",
    "py-clone", #TODO remove
] }
renamore = "0.3.2"
rfd = { version = "0.15", features = ["common-controls-v6"] }
serde = { version = "1.0.214", features = ["derive"] }
serde_json = { package = "serde_json_path_to_error", version = "0.1" }
serde_json_inner = { package = "serde_json", version = "1.0.132", features = [
    "preserve_order", # required to correctly display presets
] }
serde_with = "3.11.0"
serenity = { version = "0.12.4", default-features = false, features = ["utils"] }
smart-default = "0.7.1"
thiserror = "2"
tokio = { version = "1", features = ["rt-multi-thread"] }
wheel = { git = "https://github.com/fenhl/wheel", branch = "main", features = ["gui", "serde_json"] }

[build-dependencies]
pyo3-build-config = "0.24"
winresource = "0.1.17"

[target.'cfg(target_arch = "wasm32")'.dependencies]
zip = "2.2.0"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async_zip = { version = "0.0.17", features = ["full"] }
