[package]
name = "rust-n64-test"
version.workspace = true
edition.workspace = true

[lints.rust]
rust_2018_idioms = "deny"
unexpected_cfgs = "allow" # custom target definition
#unsafe_code = "forbid" # panic handler must be no_mangle
unused = "deny"
unused_crate_dependencies = "deny"
unused_import_braces = "deny"
unused_lifetimes = "deny"
unused_qualifications = "deny"
warnings = "deny"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.28"
