[package]
name = "ootr-cli"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
clap = { version = "4", features = ["derive"] }
mimalloc = "0.1.44"
pyo3 = { version = "0.24", features = ["auto-initialize"] }
thiserror = "2"
wheel = { git = "https://github.com/fenhl/wheel", branch = "main", features = ["pyo3"] }

[build-dependencies]
pyo3-build-config = "0.24"
